ARM_PWM = [26, 27]
ARM_DIR = [16, 17]
ARM_ADC = [35, 32]

ARM_INCHES_PER_BIT = 6 / 4096
#ARM_P = .2 * 255 * ARM_INCHES_PER_BIT #percent output / inch disparity
ARM_P = 4 * 255 * ARM_INCHES_PER_BIT #percent output / inch disparity

SCOOP_PWM = 13  # pulse width modulation
SCOOP_DIR = 14  
SCOOP_ADC = 33

BUCKET_PWM = 25
BUCKET_DIR = 23

ARM_DUTY_CYCLE = 200
BUCKET_DUTY_CYCLE = 255
SCOOP_DUTY_CYCLE = 255

ARM_LENGTH = 31.5
ARM_LIN_DIST = 6.5
LIN_UNEXTENDED_DIST = 16


# Control Buttons
ARM_FORWARD = 'f'
ARM_BACKWARD = 'b'

BUCKET_FORWARD = 'f'
BUCKET_BACKWARD = 'b'

SCOOP_FORWARD = 'f'
SCOOP_BACKWARD = 'b'
